// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikqwaksrgvmvqgzpdwti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrcXdha3NyZ3ZtdnFnenBkd3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDY3NTIsImV4cCI6MjA3MzIyMjc1Mn0.MR4g_D7Qqqn3amUymL0G0SWEhT8Ox2cMOqjrdCvHcWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});